### PR TITLE
feat : rating component

### PR DESCRIPTION
**Pull request by mohammed-sas**

### CODE REVIEW

**Review by Abhijeet43 — APPROVED** [review]
Hey, the code looks good to me...Great job!!

**Comment by mohammed-sas** [comment]
> Hey, the code looks good to me...Great job!!

thank you

**Review by VishalPatil18 — APPROVED** [review]
The code looks clean and fully functional! Great Job Mohammed 👏

**Comment by mohammed-sas** [comment]
> The code looks clean and fully functional! Great Job Mohammed 👏

thank you

**Pull request merged**
